- hosts: localhost
  gather_facts: false
  vars:
    ontap: &ontap
      hostname:       "{{ netapp_hostname }}"
      username:       "{{ netapp_username }}"
      password:       "{{ netapp_password }}"
      https:          true
      validate_certs: false
  vars_files:
    - vars.yml
    - vault_vars.yml
  collections:
    - netapp.ontap
  tasks:
    - name: Create Policy
      na_ontap_export_policy:
        state: present
        name: "{{ item.name }}"
        vserver: "{{ item.vserver }}"
        <<: *ontap
      with_items:
        "{{ nas }}"
      when: item.protocol == "nfs"
    - name: Setup rules
      na_ontap_export_policy_rule:
        state: present
        policy_name: "{{ item.name }}"
        vserver: "{{ item.vserver }}"
        client_match: "{{ item.client }}"
        ro_rule: "{{ item.ro }}"
        rw_rule: "{{ item.rw }}"
        super_user_security: "{{ item.su }}"
        protocol: "{{ item.protocol }}"
        <<: *ontap
      with_items:
        "{{ nas }}"
      when: item.protocol == "nfs"
    - name: Create nfs volume
      na_ontap_volume:
        state: present
        name: "{{ item.name }}"
        aggregate_name: "{{ item.aggr }}"
        size: "{{ item.size }}"
        size_unit: gb
        policy: "{{ 'default' if item.protocol.lower() == 'cifs' else item.name }}"
        junction_path: "/{{ item.name }}"
        space_guarantee: "none"
        percent_snapshot_space: "{{ item.percent_snapshot_space }}"
        snapshot_policy: "{{ item.snapshot_policy }}"
        vserver: "{{ item.vserver }}"
        use_rest: always
        <<: *ontap
      with_items:
        "{{ nas }}"
      when: item.protocol == "nfs"
