- hosts: localhost
  gather_facts: false
  vars:
    ontap: &ontap
      hostname:       "{{ netapp_hostname }}"
      username:       "{{ netapp_username }}"
      password:       "{{ netapp_password }}"
      https:          true
      validate_certs: false
  vars_files:
    - vars.yml
    - vault_vars.yml
  collections:
    - netapp.ontap
  tasks:
    - name: Create DNS on primary SVM
      na_ontap_dns:
        state: present
        vserver: "{{ vserver }}"
        domains: "{{ ad_domain }}"
        nameservers: "{{ nameserver }}"
        <<: *ontap
      when: ad_domain is defined
    - name: Create CIFS server
      na_ontap_cifs_server:
        state: present
        name: "{{ ad_name }}"
        vserver: "{{ vserver }}"
        service_state: started
        domain: "{{ ad_domain }}"
        ou: "{{ ou }}"
        admin_user_name: "{{ ad_user }}"
        admin_password: "{{ ad_password }}"
        <<: *ontap
      when: ad_domain is defined
    - name: Create Cifs volume
      na_ontap_volume:
        state: present
        name: "{{ item.name }}"
        aggregate_name: "{{ item.aggr }}"
        size: "{{ item.size }}"
        size_unit: gb
        policy: "{{ 'default' if item.protocol.lower() == 'cifs' else item.name }}"
        junction_path: "/{{ item.name }}"
        space_guarantee: "none"
        percent_snapshot_space: "{{ item.percent_snapshot_space }}"
        snapshot_policy: "{{ item.snapshot_policy }}"
        vserver: "{{ item.vserver }}"
        <<: *ontap
      with_items:
        "{{ nas }}"
      when: item.protocol == "cifs"
    - name: Create Share
      na_ontap_cifs:
        state: present
        share_name: "{{ item.share }}"
        path: "/{{ item.name }}"
        vserver: "{{ item.vserver }}"
        <<: *ontap
      with_items:
        "{{ nas }}"
      when: item.share is defined
